#!/bin/bash
# Jason Pittman - Scott Stout August 2019

currentUser=`ls -l /dev/console | cut -d " " -f 4`
search=$( mdfind -onlyin /Users/$currentUser -interpret -name "example-file-folder-name" )

if [ "$search" != "" ] ; then
    echo "<result>Yes\n$search</result>"
else
    echo "<result>No</result>"
fi
